# PODNAME: App::Gitc
# ABSTRACT: Git Changesets - tools for managing your git changes

=head1 INSTALLATION

Read the L<HOWTO|https://raw.github.com/GrantStreetGroup/gitc/master/HOWTO> for information on
setting up Gitc.  Example configuration files are available.

=head1 SEE ALSO

L<Gitc Wiki|https://github.com/GrantStreetGroup/gitc/wiki>

L<App::Gitc::Util>
